### ISSUE TITLE
Setup key bindings for different directories

### ISSUE THREAD

**Issue by anthrolisp** [alphapapa/org-rifle#39]
This is really awesome, thank you!
I was wondering if it were possible to custom define a couple different directories to have org-rifle search and then bind that to a particular key... such as f5 opens org-rifle for directory A, f6 opens org-rifle for directory B, etc. 
Many thanks in advance for any help!

**Comment by alphapapa** [comment]
Yes, of course.  Just define an new interactive command function that calls the appropriate rifle command, and bind it to whatever keys you like.
