### ISSUE TITLE
org-rifle-wip-org-rifle - Line breaks in text blocks?

### ISSUE THREAD

**Issue by termitereform** [alphapapa/org-rifle#40]
I've been using the WIP version of `org-rifle` for a while, and really like it -- but I've run into a weird error that may or may not be solvable.

A lot of what I do is based in text, and I use the text-centric org blocks like `#+begin_verse/#+end_verse` a lot. When I search my notes, though, words that appear in those `verse` blocks don't render or work properly. I've attached a screenshot to show how they display: 

![ex](https://user-images.githubusercontent.com/37759755/65640908-6cdedf00-dfb9-11e9-9c79-07a40e869fa2.png)

Functionality-wise, when I try to jump to one of the matches, it just goes to the start of the `verse` block rather than to the actual position of the word in the file.

I know mine is probably an edge case, but this is so close to being a perfect solution to my search and recall problems! 

All the same, thanks for the hard work!

**Comment by alphapapa** [comment]
I don't understand exactly what problem you're reporting.  You mentioned a few different things that don't sound right to me:

>  words that appear in those verse blocks don't render or work properly. I've attached a screenshot to show how they display:

I see the words in the screenshot, assuming you searched for `happy`.  What's wrong there?

> Functionality-wise, when I try to jump to one of the matches, it just goes to the start of the verse block rather than to the actual position of the word in the file.

This package has always searched by entries, i.e. headings and the text until the next heading.  It has always jumped to the heading, not individual words below the heading.

Special blocks aren't treated specially; they're just entry text.

In the title of this issue you mention line breaks, but you didn't elaborate on it.

So I don't think there are any bugs here, maybe just a misunderstanding of how the package is designed to work.

FYI, you may also find the `org-ql` package helpful.  It has some `helm-org-ql` commands.  In a way, `org-ql` is the successor to this package, and might eventually supercede it (or become the backend for it).  It also doesn't treat blocks specially,  but if that's a feature you would find useful, feel free to mention it there, and I might be able to add support for searching them.  For example, maybe a search inside a verse block could work like:

```
(verse "happy")
```
or
```
(block verse "happy")
```

**Comment by termitereform** [comment]
Yup, you're right -- I misunderstood the intended output. I was expecting org-rifle to have a certain amount of context for each match (as the various grep commands do, for example), or for it to print relevant matches on separate lines, rather than running them together. Nevermind!~

**Comment by alphapapa** [comment]
> I was expecting org-rifle to have a certain amount of context for each match

Well, it does have that.  It's also configurable, e.g. `helm-org-rifle-context-characters` and other options in `M-x customize-group RET helm-org-rifle RET`.

> or for it to print relevant matches on separate lines, rather than running them together.

That would probably be doable.  If you're interested in that, feel free to make a feature request issue and I might work on it.
