### ISSUE TITLE
Killed buffer in candidate

### ISSUE THREAD

**Issue by Kungsgeten** [alphapapa/org-rifle#43]
Hi! Sorry for posting this here, since its probably not related to `helm-org-rifle`. Anyway I tried to add an action to `helm-org-rifle` to make it possible to open `org-brain` entries directly from it. The code looks like this:

```
(defun helm-org-rifle-open-in-brain (candidate)
  (-let (((buffer . pos) candidate))
    (with-current-buffer buffer
      (goto-char pos)
      (org-brain-visualize-entry-at-pt))))

(add-to-list 'helm-org-rifle-actions
             (cons "Show entry in org-brain" 'helm-org-rifle-open-in-brain)
             t)

(defun helm-org-rifle-brain ()
  "Rifle files in `org-brain-path'."
  (interactive)
  (helm-org-rifle-directories (list org-brain-path)))
```

When I use `helm-org-rifle-brain` and then use the `Show entry in org-brain` action, the `buffer` part of `candidate` in `helm-org-rifle-open-in-brain` is a killed buffer. Do you have any experience with this behaviour?

**Comment by alphapapa** [comment]
Hi Erik,

No problem, it might be a bug that needs to be fixed.

What's your setting for `helm-org-rifle-close-unopened-file-buffers`?  Does it happen if you try to use the action on a candidate that's in a buffer which was already open when you called the `helm-org-rifle-brain` command?

BTW, you might also be interested in trying `org-ql` as a backend, since it's more powerful and faster than `helm-org-rifle`.  Basically, the only advantage of `helm-org-rifle` at the moment is the way it displays context, which is a feature I may add to `org-ql` in the future.

**Comment by Kungsgeten** [comment]
Thanks for the quick answer! Indeed if I have an open buffer it seems to works fine. The value of `helm-org-rifle-close-unopened-file-buffers` is `t` (default value), but if I set it to `nil` it all works even if the buffer isn't open. However I also tried to use `let` to locally set the variable inside the `helm-org-rifle-open-in-brain` function, but that didn't seem to work.

I've actually fiddled a little bit with `org-ql` too. It seems like a really nice package, and I've thought about the possibility of using it as the "search engine" for `org-brain` since that would probably declutter the code. However `org-brain` has this concept of "file entries" (the part above the first headline in a file) which `org-ql` (and `org-mode` in general) doesn't seem to handle very well. @Whil- has submitted a patch to `org-mode` which in my understanding will allow files to have an ID, properties, etc. That would probably make headlines and "file entries" more equal. Another aspect is that I try to have few dependencies to other packages, but I'm starting to think that may be stubborn and dumb :)

I tried using `org-sidebar` to make a sidebar for `org-brain` (using the `org-sidebar` function with `org-ql` items). One issue here was that the sidebar seems to be in `fundamental-mode`, which seems odd to me.

**Comment by alphapapa** [comment]
> Thanks for the quick answer! Indeed if I have an open buffer it seems to works fine. The value of `helm-org-rifle-close-unopened-file-buffers` is `t` (default value), but if I set it to `nil` it all works even if the buffer isn't open. 

Yep, that's how it's supposed to work.

> However I also tried to use `let` to locally set the variable inside the `helm-org-rifle-open-in-brain` function, but that didn't seem to work.

That's not the correct scope in which to bind the variable.  It must be bound around the search command, not the action command.

> I've actually fiddled a little bit with `org-ql` too. It seems like a really nice package, and I've thought about the possibility of using it as the "search engine" for `org-brain` since that would probably declutter the code. However `org-brain` has this concept of "file entries" (the part above the first headline in a file) which `org-ql` (and `org-mode` in general) doesn't seem to handle very well.

`org-ql` is intended to search outlines, not pre-outline matter in a file.

> @Whil- has submitted a patch to `org-mode` which in my understanding will allow files to have an ID, properties, etc. That would probably make headlines and "file entries" more equal. 

Yes, we've been discussing Gustav's proposal on the mailing list.  Suffice it to say here that opinions are mixed.  ;)

> Another aspect is that I try to have few dependencies to other packages, but I'm starting to think that may be stubborn and dumb :)

For packages intended to be put in Emacs/Org core, that makes sense, but for MELPA packages, IMO it makes sense to use the available tools to simplify one's code.

> I tried using `org-sidebar` to make a sidebar for `org-brain` (using the `org-sidebar` function with `org-ql` items). One issue here was that the sidebar seems to be in `fundamental-mode`, which seems odd to me.

The sidebar buffers have no natural major mode at this time; they aren't Org buffers, nor are they Agenda buffers.  `fundamental-mode` is the default major mode for Emacs buffers.

I'll probably be rewriting `org-sidebar`'s buffers to use more of `org-ql`, in which case they'll be `org-ql-view` buffers in `org-agenda-mode`.

**Comment by Kungsgeten** [comment]
From my understanding the package (helm-org-rifle) seems to work as intended. I had just missed the `helm-org-rifle-close-unopened-file-buffers` variable. Thank you for your help!
