### ISSUE TITLE
[Feature Request] Only show the headings

### ISSUE THREAD

**Issue by grigorievich** [alphapapa/org-rifle#48]
Hi! I thought, is it possible to view the outline of the file with `helm-org-rifle-current-buffer'? `helm-org-in-buffer-headings' does that (from `helm-org' package in melpa), but it fails to preserve the structure of the tree, sorting everything in alphabetical order. A keyword in the input field (or even a seperate function) would work very nicely, I think, allowing both search customization and the ability to have the whole outline right in front of you when you need it.

**Comment by alphapapa** [comment]
> helm-org-in-buffer-headings' does that (from `helm-org' package in melpa), but it fails to preserve the structure of the tree, sorting everything in alphabetical order.

No, it doesn't sort in alphabetical order.

**Comment by grigorievich** [comment]
> No, it doesn't sort in alphabetical order.

You are right. I have updated the packages and the sort reflects the tree structure now (still resorts to alphabetical when searching, though).

My main problem with it however is that when searching for a subheading, the parent heading info is lost. That is, if I search for a subheading, I am not always sure to which branch it belongs. In org-rifle this is already solved by showing "heading/subheading". The dramatic version of the same downside is when some subheadings happen to be the same:

```
* heading A
** subheading
* heading B
** subheading
```

where the search yields

```
** subheading
** subheading
```

While I could file a feature request for helm-org (probably should anyway), org-rifle doesn't have this problem in the first place.

**Comment by alphapapa** [comment]
```
helm-org-format-outline-path is a variable defined in ‘helm-org.el’.
Its value is t
Original value was nil

Documentation:
Show all org level as path.

You can customize this variable.
```

**Comment by grigorievich** [comment]
Thought that would have been a default if it existed! Now it's like I want it and the colored highligting appears for each heading as well, thank you!

**Comment by alphapapa** [comment]
It's not a default because it decreases performance to format the path for every heading.  Be sure to check `M-x customize-group` for packages you use, because they usually have settings for things like this.

**Comment by grigorievich** [comment]
@alphapapa I see, thanks!
