### ISSUE TITLE
org helm rifle can show 1or2 character search result but org helm rifle occur show nothing

### ISSUE THREAD

**Issue by Michael-ABC** [alphapapa/org-rifle#49]
org helm rifle: key words can less than 2 characters 

but org helm rifle occur 
if key words less than 2 characters show nothing 

example:
test:
hello word
hehehe

search "he"
org helm rifle: show hello word and hehehe

org helm rifle occur: show nothing

**Comment by alphapapa** [comment]
There is a minimum input size of 3.  See https://github.com/alphapapa/org-rifle/blob/abc14bb85427a6585aa354894eaef6926881d585/helm-org-rifle.el#L1280
