### ISSUE TITLE
Speed command shortcuts do not work in helm-rifle-occur-buffer

### ISSUE THREAD

**Issue by guibor** [alphapapa/org-rifle#50]
When the buffer is generated by using one of the helm-org-rifle-occur-* , the buffer that is created does not have the affordances to allow outline-next and outline-previous to work (and thus enable navigation using speed commands)

**Comment by alphapapa** [comment]
You have identified a symptom but probably not the cause.

Anyway, occur buffers are not real Org buffers, and they are not editable, so actual Org commands are not intended to work.  There are already "speed commands" built-in.  See `helm-org-rifle-occur-map`.

**Comment by guibor** [comment]
Right, that is the symptom - at least in my case the commands in the helm-org-rifle-occur-map do not work (meaning that C-n and C-p do not move forward and backwards in the occur buffer)

**Comment by alphapapa** [comment]
I just tested in a clean configuration, and `C-n` and `C-p` work like in any other Emacs buffer.

**Comment by alphapapa** [comment]
There may have been some misunderstanding about the commands which are intended to work in the occur buffers, but I think I found the problem you were encountering.  That should fix it.  Please let me know if it works for you.  Thanks for reporting.

**Comment by guibor** [comment]
Thanks! This works.

And also:  this is a great package! I use it every day now.

**Comment by alphapapa** [comment]
Thanks, I'm glad it's helpful to you.

I also recommend trying my other search package, https://github.com/alphapapa/org-ql
