### ISSUE TITLE
Question: Is it possible to search #+title

### ISSUE THREAD

**Issue by djelenc** [alphapapa/org-rifle#55]
Hi. This is a great feature. It really helps to navigate my collection of `.org` files. As I move towards `org-roam` format of writing notes, I find myself writing the title of documents in the `+title: ` at the beginning of the org file.

So my question is the following: Is is possible to also search through titles that are specified as `#+title: My title`?

**Comment by alphapapa** [comment]
No.  This package searches by heading, not by file.  In that respect, it is contrary to the one-note-per-file paradigm of `org-roam`.

**Comment by djelenc** [comment]
Thank you
