### ISSUE TITLE
tag inheritance and/or file matching

### ISSUE THREAD

**Issue by basaran** [alphapapa/org-rifle#61]
Hello,

Thank you for the org-rifle. It's really great. Could you advise if the tag search allows for inheritance? I couldn't get this to work with:

```#+FILETAGS: :postgresql```

![image](https://user-images.githubusercontent.com/30809170/96953725-d7fe2c00-14bf-11eb-912d-47b4f75fb814.png)

I'm trying to ease my searching while going through several different cheatsheets so I can rifle with:

:postgresql hba

![image](https://user-images.githubusercontent.com/30809170/96953772-f06e4680-14bf-11eb-8fa2-40bc0ca4772c.png)

But it's not matching the hba.conf header. I also haven't had much luck with matching the filename itself.

![image](https://user-images.githubusercontent.com/30809170/96953969-67a3da80-14c0-11eb-8896-4efb72b6f8bf.png)

I can add the tags manually per heading if there isn't a way around this. Thank you again for your time.

**Comment by alphapapa** [comment]
Hi,

Thanks for the kind words.  I'm glad org-rifle is useful to you.

Regarding this issue, please see #34.  In general, I recommend using org-ql now, which is more featureful and faster than org-rifle (and it supports tag inheritance; see its documentation).  See, e.g. the `helm-org-ql` command, in which you could type a query like `dba itags:postgresql` or `dba category:postgresql` or `dba file:postgres`.
