### ISSUE TITLE
helm-org-rifle-directories: how to add many directories?

### ISSUE THREAD

**Issue by AtomicNess123** [alphapapa/org-rifle#75]
I couldn't manage to do this although I read the Readme. Could you give an example? Thanks!

**Comment by alphapapa** [comment]
The issue tracker is not intended for general support questions.  If you ask here, the burden of answering falls solely on me, and the benefit of any answer is only offered to you.  Please ask in an appropriate forum like https://old.reddit.com/r/emacs or https://matrix.to/#/#emacs:matrix.org where other people can also offer help and learn from the answers.
