### ISSUE TITLE
Fix warning "Helm source <file>: after-init-hook Should be defined as a symbol 

### ISSUE THREAD

**Issue by darim1** [alphapapa/org-rifle#78]
### What happened?

I observe warnings, when trying to search my org files with helm-org-rifle:

```
Warning (emacs): Helm source ‘file1.org’: after-init-hook Should be defined as a symbol Disable showing Disable logging
Warning (emacs): Helm source ‘file2.org’: after-init-hook Should be defined as a symbol Disable showing Disable logging
...
```
The only after-init hook I employ is a key binding:

```
(add-hook 'helm-after-initialize-hook
          (lambda()
            (define-key helm-buffer-map (kbd "ESC") 'helm-keyboard-quit)
            (define-key helm-M-x-map (kbd "ESC") 'helm-keyboard-quit)
            (define-key helm-map (kbd "ESC") 'helm-keyboard-quit)))
```

I've already disabled it, with no luck.

### How to reproduce?

1. Install helm-org-rifle
2. define some agenda files
3. run helm-org-rifle
4. Observe the warnings, before the pattern can be entered

### Helm Version

Melpa

### Emacs Version

Emacs-28/29

### OS

Windows

**Comment by alphapapa** [comment]
Please see #77.  Thanks.
