### ISSUE TITLE
Warning (emacs): ... after-init-hook Should be defined as a symbol

### ISSUE THREAD

**Issue by Ypot** [alphapapa/org-rifle#81]
Hi

After trying other searching options, I have come back to org-rifle. I like its real-time results, its options, and always works.

I am receiving a warning for each file of the agenda, when I eval _helm-org-rifle-agenda-files_:
`
⛔ Warning (emacs): Helm source ‘1-file.org’: after-init-hook Should be defined as a symbol`

And it is giving me these warnings too:
```
⛔ Warning (comp): helm-core.el:6610:14: Warning: `inhibit-point-motion-hooks' is an obsolete variable (as of 25.1); use `cursor-intangible-mode' or `cursor-sensor-mode' instead
⛔ Warning (comp): helm-core.el:7161:47: Warning: `special-display-buffer-names' is an obsolete variable (as of 24.3); use `display-buffer-alist' instead.
⛔ Warning (comp): helm-core.el:7161:23: Warning: `special-display-regexps' is an obsolete variable (as of 24.3); use `display-buffer-alist' instead.
```

**Comment by alphapapa** [comment]
Hello,

Welcome back, I guess.  :)  Curious, have you tried `org-ql`, especially its newer commands like `org-ql-find`?  I intend these to obsolete `org-rifle` eventually, and it largely does already.

Anyway, I think these warnings are coming from Helm, not from this package.

**Comment by Ypot** [comment]
Hi!
Thanks, maybe I will try to open an issue on helm site.

Yes, I changed from org-rifle, to org-ql (org-ql-find-in-agenda). But lately it is hanging (it starts making a real-time search while I type, but suddenly it stops updating the results). After that, I have been using (my-multi-occur-in-matching-buffers). But I was missing our old rifle.

I have been reading again the readme.org, and I think this kind of functions are not available in other search "engines":
https://github.com/alphapapa/org-rifle#tips

**Comment by alphapapa** [comment]
> Hi! Thanks, maybe I will try to open an issue on helm site.

Yes, please do, otherwise the issue might go unresolved.  Thierry is usually very responsive to reports.

> Yes, I changed from org-rifle, to org-ql (org-ql-find-in-agenda). But lately it is hanging (it starts making a real-time search while I type, but suddenly it stops updating the results).

That is probably this issue, which should get fixed eventually: https://github.com/alphapapa/org-ql/issues/350  Please monitor that issue and try it again after it's fixed.

> I have been reading again the readme.org, and I think this kind of functions are not available in other search "engines": https://github.com/alphapapa/org-rifle#tips

Most of those are or will be available in org-ql's commands as well.  If there's a particular one you're missing, please open an issue on the org-ql tracker and we can talk about it.

Since AFAICT the issue reported here is a Helm one, I'll close this issue now, but please let me know if you find otherwise.

**Comment by thierryvolpiatto** [comment]
Hello @alphapapa here is the original issue and it seems you didn't fixed it ;-)
https://github.com/alphapapa/org-rifle/pull/77

**Comment by alphapapa** [comment]
Fixed on stable and master now.  Thanks to all.
